name: Build & Deploy

on:
  push:
    branches:
      main

jobs:

  build-ios:
    name: Build iOS and Deploy
    runs-on: macos-latest

    steps:
      - name: Build iOS
        run: |
          xcodebuild build \
            - workspace "YoutubeDL.xcworkspace" \
            - scheme "YoutubeDL" \
            - sdk iphoneos \
            - destination 'platform=iOS,OS=17.0' \
            - configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO   
