name: Build & Deploy

on:
  push:
    branches:
      main

jobs:

  build-ios:
    name: Build iOS and Deploy
    runs-on: macos-latest

    steps:
      - name: Build iOS
        run: |
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild build \
            -"$filetype_parameter" "$file_to_build" \
            -scheme "YoutubeDL" \
            -sdk iphoneos \
            -destination 'platform=iOS,OS=17.0' \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO   
