name: Build Unsigned iOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
        
    - name: Build unsigned app
      run: |
        xcodebuild \
          -project YoutubeDL.xcodeproj \
          -scheme "YoutubeDL" \
          -sdk iphoneos \
          -configuration Release \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          build

    - name: Export unsigned .app bundle
      run: |
        cd ios
        mkdir Result
        cp -R "build/Release-iphoneos/YoutubeDL.app" "./Result/YoutubeDL.app"
        cd ..

    - name: Archive and upload .app file
      uses: actions/upload-artifact@v4
      with:
        name: unsigned-ios-app
        path: ./result/   
